/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Datos.DatosAltaBien;
import Datos.DatosArea;
import static Vista.ConsultaBienes.comboAreas;
import static Vista.Principal.Escritorio;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mayra
 */
public class ConsultaAsignacion extends javax.swing.JInternalFrame {

    Controlador c = new Controlador();
    DatosAltaBien datBienes = new DatosAltaBien();
    DatosArea datArea = new DatosArea();
    String seleccion = "";

    /**
     * Creates new form ConsultaAsignacion
     */
    public ConsultaAsignacion(String select) {
        initComponents();
        datArea.mostrarComboAreas(comboAreas);
        seleccion = select;
        if (seleccion.equals("CambioAsig")) {
            lbTitulo.setText("Cambio de Asignación de Bienes");
        } else if (seleccion.equals("ConsultaAsig")) {
            lbTitulo.setText("Consulta de Asignación de Bienes");
        }
    }

    public void mostrar(String buscar) {
        try {

            if (comboAreas.getSelectedItem() == "") {
                JOptionPane.showMessageDialog(null, "Selecciona un área existente");
            } else {
                String area = comboAreas.getItemAt(comboAreas.getSelectedIndex()).getNombre();

                DefaultTableModel tb = c.cargar_tabla_AsignacionBienes_nombre(area, buscar);
                tbDatos.setModel(tb);

                tbDatos.getColumnModel().getColumn(0).setPreferredWidth(40);
                tbDatos.getColumnModel().getColumn(1).setPreferredWidth(180);
                tbDatos.getColumnModel().getColumn(2).setPreferredWidth(180);

                tbDatos.getColumnModel().getColumn(3).setMaxWidth(0);
                tbDatos.getColumnModel().getColumn(3).setMinWidth(0);
                tbDatos.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(0);
                tbDatos.getTableHeader().getColumnModel().getColumn(3).setMinWidth(0);

                tbDatos.getColumnModel().getColumn(4).setMaxWidth(0);
                tbDatos.getColumnModel().getColumn(4).setMinWidth(0);
                tbDatos.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(0);
                tbDatos.getTableHeader().getColumnModel().getColumn(4).setMinWidth(0);

                tbDatos.getColumnModel().getColumn(5).setPreferredWidth(180);

                tbDatos.getColumnModel().getColumn(6).setMaxWidth(0);
                tbDatos.getColumnModel().getColumn(6).setMinWidth(0);
                tbDatos.getTableHeader().getColumnModel().getColumn(6).setMaxWidth(0);
                tbDatos.getTableHeader().getColumnModel().getColumn(6).setMinWidth(0);

                tbDatos.getColumnModel().getColumn(7).setMaxWidth(0);
                tbDatos.getColumnModel().getColumn(7).setMinWidth(0);
                tbDatos.getTableHeader().getColumnModel().getColumn(7).setMaxWidth(0);
                tbDatos.getTableHeader().getColumnModel().getColumn(7).setMinWidth(0);

                tbDatos.getColumnModel().getColumn(8).setMaxWidth(0);
                tbDatos.getColumnModel().getColumn(8).setMinWidth(0);
                tbDatos.getTableHeader().getColumnModel().getColumn(8).setMaxWidth(0);
                tbDatos.getTableHeader().getColumnModel().getColumn(8).setMinWidth(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        comboAreas = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(41, 55, 61));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Search_24px.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setOpaque(true);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Dato: ");

        tbDatos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int columnIndex){
                return false;
            }
        };
        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbDatos.getTableHeader().setReorderingAllowed(false);
        tbDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDatosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbDatosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbDatos);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Área:");

        comboAreas.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        comboAreas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboAreasItemStateChanged(evt);
            }
        });
        comboAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAreasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(comboAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(41, 55, 61));

        lbTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(lbTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String filtro;
        filtro = txtBuscar.getText();
        mostrar(filtro);

    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String filtro;
        filtro = txtBuscar.getText();
        mostrar(filtro);
        txtBuscar.setText("");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tbDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDatosMouseClicked
        if (seleccion.equals("CambioAsig")) {

            if (evt.getClickCount() == 2) {
                int fila = tbDatos.getSelectedRow();
                String idvaleR, nombre, ctt, area, clave, curp, cantidadt, valort;
                idvaleR = tbDatos.getValueAt(fila, 0).toString();
                nombre = tbDatos.getValueAt(fila, 5).toString();
                ctt = tbDatos.getValueAt(fila, 3).toString();
                area = tbDatos.getValueAt(fila, 2).toString();
                clave = tbDatos.getValueAt(fila, 4).toString();
                curp = tbDatos.getValueAt(fila, 6).toString();
                cantidadt = tbDatos.getValueAt(fila, 7).toString();
                valort = tbDatos.getValueAt(fila, 8).toString();

                this.dispose();
                ValeActivo form = null;

                try {
                    form = new ValeActivo("cambioAsig",idvaleR);
                ValeActivo.txtIdValeR.setText(idvaleR);
                ValeActivo.txtName.setText(nombre);
                ValeActivo.txtCTT.setText(ctt);
                ValeActivo.txtArea.setText(area);
                ValeActivo.txtclave.setText(clave);
                ValeActivo.txtcurp.setText(curp);
                ValeActivo.txtCanTotal.setText(cantidadt);
                ValeActivo.txtValTotal.setText(valort);
                } catch (SQLException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                Escritorio.add(form);
                form.setClosable(true);
                form.setIconifiable(true);
                form.toFront();
                form.setVisible(true);

            }
        } else {
            //Consulta
        }
    }//GEN-LAST:event_tbDatosMouseClicked

    private void tbDatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDatosMousePressed

    }//GEN-LAST:event_tbDatosMousePressed

    private void comboAreasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboAreasItemStateChanged
        mostrar("");
        txtBuscar.setText("");
    }//GEN-LAST:event_comboAreasItemStateChanged

    private void comboAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAreasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAreasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    public static javax.swing.JComboBox<DatosArea> comboAreas;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTable tbDatos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
