/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();
        lblAcceso = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mUsuarios = new javax.swing.JMenu();
        sUsuarios = new javax.swing.JMenuItem();
        mAreas = new javax.swing.JMenu();
        sAreas = new javax.swing.JMenuItem();
        mPersonal = new javax.swing.JMenu();
        sPersonal = new javax.swing.JMenuItem();
        sConsultasPersonal = new javax.swing.JMenuItem();
        mReportes = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        sEtiqueta = new javax.swing.JMenuItem();
        sEtiquetaArea = new javax.swing.JMenuItem();
        sEtiquetasAll = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        rAltaBienesFecha = new javax.swing.JMenuItem();
        rAltaBienesArea = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        rBajaBienesFecha = new javax.swing.JMenuItem();
        rBajaBienesArea = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        rConsumiblesFecha = new javax.swing.JMenuItem();
        rConsumiblesCategoria = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        rAsignBienesFecha = new javax.swing.JMenuItem();
        rAsignBienesPersona = new javax.swing.JMenuItem();
        rAsignBienesArea = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        rSalConsumiblesFecha = new javax.swing.JMenuItem();
        rSalConsumiblesPersonal = new javax.swing.JMenuItem();
        rSalConsumiblesArea = new javax.swing.JMenuItem();
        mBienes = new javax.swing.JMenu();
        sBienes = new javax.swing.JMenuItem();
        sBajasBienes = new javax.swing.JMenuItem();
        sValeRes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        sConsultasBienes = new javax.swing.JMenuItem();
        wConsultaAsig = new javax.swing.JMenuItem();
        sCambioAsig = new javax.swing.JMenuItem();
        menuC = new javax.swing.JMenu();
        mConsumibles = new javax.swing.JMenuItem();
        mConsultas = new javax.swing.JMenuItem();
        sVale = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");
        setIconImages(null);

        Escritorio.setBackground(new java.awt.Color(255, 255, 255));
        Escritorio.setPreferredSize(new java.awt.Dimension(374, 374));

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Acceso:");

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombre.setText(" ");

        lblIdUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIdUsuario.setText(" ");

        lblAcceso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAcceso.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(lblNombre)
                .addComponent(jLabel3)
                .addComponent(lblAcceso)
                .addComponent(jLabel2)
                .addComponent(lblIdUsuario))
        );

        Escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 352, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(41, 55, 61));
        jMenuBar1.setBorder(null);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(464, 40));

        mUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        mUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        mUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Male_User_24px.png"))); // NOI18N
        mUsuarios.setText("Usuarios");
        mUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        sUsuarios.setText("Agregar");
        sUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sUsuariosActionPerformed(evt);
            }
        });
        mUsuarios.add(sUsuarios);

        jMenuBar1.add(mUsuarios);

        mAreas.setBackground(new java.awt.Color(255, 255, 255));
        mAreas.setForeground(new java.awt.Color(255, 255, 255));
        mAreas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Flow_Chart_24px.png"))); // NOI18N
        mAreas.setText("Areas");
        mAreas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        sAreas.setText("Agregar");
        sAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAreasActionPerformed(evt);
            }
        });
        mAreas.add(sAreas);

        jMenuBar1.add(mAreas);

        mPersonal.setBackground(new java.awt.Color(255, 255, 255));
        mPersonal.setForeground(new java.awt.Color(255, 255, 255));
        mPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_People_24px.png"))); // NOI18N
        mPersonal.setText("Personal");
        mPersonal.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        sPersonal.setText("Agregar");
        sPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPersonalActionPerformed(evt);
            }
        });
        mPersonal.add(sPersonal);

        sConsultasPersonal.setText("Consultas");
        sConsultasPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sConsultasPersonalActionPerformed(evt);
            }
        });
        mPersonal.add(sConsultasPersonal);

        jMenuBar1.add(mPersonal);

        mReportes.setBackground(new java.awt.Color(255, 255, 255));
        mReportes.setForeground(new java.awt.Color(255, 255, 255));
        mReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Documents_24px.png"))); // NOI18N
        mReportes.setText("Reportes");
        mReportes.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mReportes.add(jSeparator1);

        jMenu1.setText("Etiquetas");

        sEtiqueta.setText("Generar etiqueta por No. Inventario");
        sEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sEtiquetaActionPerformed(evt);
            }
        });
        jMenu1.add(sEtiqueta);

        sEtiquetaArea.setText("Generar etiqueta por area");
        sEtiquetaArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sEtiquetaAreaActionPerformed(evt);
            }
        });
        jMenu1.add(sEtiquetaArea);

        sEtiquetasAll.setText("Generar etiqueta por personal");
        sEtiquetasAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sEtiquetasAllActionPerformed(evt);
            }
        });
        jMenu1.add(sEtiquetasAll);

        mReportes.add(jMenu1);

        jMenu3.setText("Alta de bienes");

        rAltaBienesFecha.setText("Por Fecha");
        rAltaBienesFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAltaBienesFechaActionPerformed(evt);
            }
        });
        jMenu3.add(rAltaBienesFecha);

        rAltaBienesArea.setText("Por Área");
        rAltaBienesArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAltaBienesAreaActionPerformed(evt);
            }
        });
        jMenu3.add(rAltaBienesArea);

        mReportes.add(jMenu3);

        jMenu4.setText("Baja de bienes");

        rBajaBienesFecha.setText("Por Fecha");
        rBajaBienesFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBajaBienesFechaActionPerformed(evt);
            }
        });
        jMenu4.add(rBajaBienesFecha);

        rBajaBienesArea.setText("Por Área");
        rBajaBienesArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBajaBienesAreaActionPerformed(evt);
            }
        });
        jMenu4.add(rBajaBienesArea);

        mReportes.add(jMenu4);

        jMenu5.setText("Consumibles");

        rConsumiblesFecha.setText("Fecha");
        rConsumiblesFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rConsumiblesFechaActionPerformed(evt);
            }
        });
        jMenu5.add(rConsumiblesFecha);

        rConsumiblesCategoria.setText("Categoría");
        rConsumiblesCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rConsumiblesCategoriaActionPerformed(evt);
            }
        });
        jMenu5.add(rConsumiblesCategoria);

        mReportes.add(jMenu5);

        jMenu6.setText("Asingnación de bienes");

        rAsignBienesFecha.setText("Por Fecha");
        rAsignBienesFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAsignBienesFechaActionPerformed(evt);
            }
        });
        jMenu6.add(rAsignBienesFecha);

        rAsignBienesPersona.setText("Por Persona");
        rAsignBienesPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAsignBienesPersonaActionPerformed(evt);
            }
        });
        jMenu6.add(rAsignBienesPersona);

        rAsignBienesArea.setText("Por Área");
        rAsignBienesArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAsignBienesAreaActionPerformed(evt);
            }
        });
        jMenu6.add(rAsignBienesArea);

        mReportes.add(jMenu6);

        jMenu7.setText("Salida de Consumibles");

        rSalConsumiblesFecha.setText("Por Fecha");
        rSalConsumiblesFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSalConsumiblesFechaActionPerformed(evt);
            }
        });
        jMenu7.add(rSalConsumiblesFecha);

        rSalConsumiblesPersonal.setText("Por Persona");
        rSalConsumiblesPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSalConsumiblesPersonalActionPerformed(evt);
            }
        });
        jMenu7.add(rSalConsumiblesPersonal);

        rSalConsumiblesArea.setText("Por Área");
        rSalConsumiblesArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSalConsumiblesAreaActionPerformed(evt);
            }
        });
        jMenu7.add(rSalConsumiblesArea);

        mReportes.add(jMenu7);

        jMenuBar1.add(mReportes);

        mBienes.setBackground(new java.awt.Color(255, 255, 255));
        mBienes.setForeground(new java.awt.Color(255, 255, 255));
        mBienes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Organization_24px.png"))); // NOI18N
        mBienes.setText("Activo Fijo");
        mBienes.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        sBienes.setText("Altas y Modificaciones");
        sBienes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBienesActionPerformed(evt);
            }
        });
        mBienes.add(sBienes);

        sBajasBienes.setText("Bajas");
        sBajasBienes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBajasBienesActionPerformed(evt);
            }
        });
        mBienes.add(sBajasBienes);

        sValeRes.setText("Vale de Resguardo");
        sValeRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sValeResActionPerformed(evt);
            }
        });
        mBienes.add(sValeRes);

        jMenu2.setText("Consultas");

        sConsultasBienes.setText("Consultas Bienes");
        sConsultasBienes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sConsultasBienesActionPerformed(evt);
            }
        });
        jMenu2.add(sConsultasBienes);

        wConsultaAsig.setText("Consultas Asignación de Bienes");
        wConsultaAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wConsultaAsigActionPerformed(evt);
            }
        });
        jMenu2.add(wConsultaAsig);

        mBienes.add(jMenu2);

        sCambioAsig.setText("Cambio de Asignación");
        sCambioAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCambioAsigActionPerformed(evt);
            }
        });
        mBienes.add(sCambioAsig);

        jMenuBar1.add(mBienes);

        menuC.setBackground(new java.awt.Color(255, 255, 255));
        menuC.setForeground(new java.awt.Color(255, 255, 255));
        menuC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Paid_24px_1.png"))); // NOI18N
        menuC.setText("Consumibles");
        menuC.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        mConsumibles.setText("Altas");
        mConsumibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsumiblesActionPerformed(evt);
            }
        });
        menuC.add(mConsumibles);

        mConsultas.setText("Consultas");
        mConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultasActionPerformed(evt);
            }
        });
        menuC.add(mConsultas);

        sVale.setText("Generar Vale");
        sVale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sValeActionPerformed(evt);
            }
        });
        menuC.add(sVale);

        jMenuBar1.add(menuC);

        mSalir.setBackground(new java.awt.Color(255, 255, 255));
        mSalir.setForeground(new java.awt.Color(255, 255, 255));
        mSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Exit_24px.png"))); // NOI18N
        mSalir.setText("Salir");
        mSalir.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sUsuariosActionPerformed
        Usuarios form = null;
        try {
            form = new Usuarios();
            Escritorio.add(form);

            form.setClosable(true);
            form.setIconifiable(true);
           
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_sUsuariosActionPerformed

    private void mConsumiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsumiblesActionPerformed
        Consumibles form = null;
        try {
            form = new Consumibles();
             Escritorio.add(form);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_mConsumiblesActionPerformed

    private void mConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultasActionPerformed
        ConsultaConsumibles form = null;
        try {
            form = new ConsultaConsumibles();
             Escritorio.add(form);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_mConsultasActionPerformed

    private void sAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAreasActionPerformed
        Areas form = null;
        try {
            form = new Areas();
            Escritorio.add(form);

            form.setClosable(true);
            form.setIconifiable(true);
           
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_sAreasActionPerformed

    private void mSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSalirMouseClicked
       int i = JOptionPane.showConfirmDialog(this,  "¿Desea Salir?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            //System.exit(0);
            this.dispose();
            Login login = new Login();
            login.setVisible(true);
        } 
    }//GEN-LAST:event_mSalirMouseClicked

    private void sPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPersonalActionPerformed
        Personal form = null;
        try {
            form = new Personal();
            Escritorio.add(form);

            form.setClosable(true);
            form.setIconifiable(true);
           
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_sPersonalActionPerformed

    private void sConsultasPersonalActionPerformed(java.awt.event.ActionEvent evt) {                                                   
      ConsultaPersonal form = null;
        try {
            form = new ConsultaPersonal("");
            Escritorio.add(form);

            form.setClosable(true);
            form.setIconifiable(true);
           
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.toFront();
        form.setVisible(true);  
                                                     
    }
    private void sBienesActionPerformed(java.awt.event.ActionEvent evt) {                                        
        AltaBienes form = null;
        try {
            form = new AltaBienes();
            Escritorio.add(form);

            form.setClosable(true);
            form.setIconifiable(true);
           
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.toFront();
        form.setVisible(true);
    }

    private void sConsultasBienesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sConsultasBienesActionPerformed
        ConsultaBienes form = null;
        try {
            form = new ConsultaBienes("Consulta");
            Escritorio.add(form);

            form.setClosable(true);
            form.setIconifiable(true);           
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_sConsultasBienesActionPerformed

    private void sValeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sValeActionPerformed
        ValesAlmacen form = null;
        try {
            form = new ValesAlmacen();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Escritorio.add(form);
        form.setClosable(true);
        form.setIconifiable(true);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_sValeActionPerformed

    private void sBajasBienesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBajasBienesActionPerformed
        BajaBienes form = null;
        try {
            form = new BajaBienes();
            Escritorio.add(form);

            form.setClosable(true);
            form.setIconifiable(true);
           
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_sBajasBienesActionPerformed

    private void sValeResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sValeResActionPerformed
        ValeActivo form = null;
        try {
            form = new ValeActivo("AgregarAsig","");
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Escritorio.add(form);
        form.setClosable(true);
        form.setIconifiable(true);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_sValeResActionPerformed

    private void sEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sEtiquetaActionPerformed
        EtiquetaInventario form = null;
        form = new EtiquetaInventario();
        Escritorio.add(form);
        form.setClosable(true);
        form.setIconifiable(true);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_sEtiquetaActionPerformed

    private void sEtiquetaAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sEtiquetaAreaActionPerformed
        EtiquetasArea form = null;
        form = new EtiquetasArea();
        Escritorio.add(form);
        form.setClosable(true);
        form.setIconifiable(true);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_sEtiquetaAreaActionPerformed

    private void sEtiquetasAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sEtiquetasAllActionPerformed
      EtiquetasPersonal form = null;
        form = new EtiquetasPersonal();
        Escritorio.add(form);
        form.setClosable(true);
        form.setIconifiable(true);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_sEtiquetasAllActionPerformed

    private void wConsultaAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wConsultaAsigActionPerformed
        ConsultaAsignacion form = null;
        form = new ConsultaAsignacion("ConsultaAsig");
        Escritorio.add(form);
        form.setClosable(true);
        form.setIconifiable(true);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_wConsultaAsigActionPerformed

    private void sCambioAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCambioAsigActionPerformed
        ConsultaAsignacion form = null;
        form = new ConsultaAsignacion("CambioAsig");
        Escritorio.add(form);
        form.setClosable(true);
        form.setIconifiable(true);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_sCambioAsigActionPerformed

    private void rAltaBienesFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAltaBienesFechaActionPerformed
        ReportesFecha form = null;
        form = new ReportesFecha("AltaBienes");
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_rAltaBienesFechaActionPerformed

    private void rAltaBienesAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAltaBienesAreaActionPerformed
        ReportesArea form = null;
        form = new ReportesArea("AltaBienes");
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_rAltaBienesAreaActionPerformed

    private void rBajaBienesFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBajaBienesFechaActionPerformed
        ReportesFecha form = null;
        form = new ReportesFecha("BajaBienes");
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_rBajaBienesFechaActionPerformed

    private void rConsumiblesCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rConsumiblesCategoriaActionPerformed
        ReportesCategoria form = null;
        form = new ReportesCategoria();
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_rConsumiblesCategoriaActionPerformed

    private void rAsignBienesFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAsignBienesFechaActionPerformed
        ReportesFecha form = null;
        form = new ReportesFecha("AsigBienes");
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_rAsignBienesFechaActionPerformed

    private void rSalConsumiblesAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSalConsumiblesAreaActionPerformed
        ReportesArea form = null;
        form = new ReportesArea("SalConsumibles");
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_rSalConsumiblesAreaActionPerformed

    private void rBajaBienesAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBajaBienesAreaActionPerformed
        ReportesArea form = null;
        form = new ReportesArea("BajaBienes");
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_rBajaBienesAreaActionPerformed

    private void rAsignBienesAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAsignBienesAreaActionPerformed
        ReportesArea form = null;
        form = new ReportesArea("AsigBienes");
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_rAsignBienesAreaActionPerformed

    private void rConsumiblesFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rConsumiblesFechaActionPerformed
        ReportesFecha form = null;
        form = new ReportesFecha("Consumibles");
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_rConsumiblesFechaActionPerformed

    private void rSalConsumiblesFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSalConsumiblesFechaActionPerformed
        ReportesFecha form = null;
        form = new ReportesFecha("SalConsumibles");
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_rSalConsumiblesFechaActionPerformed

    private void rAsignBienesPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAsignBienesPersonaActionPerformed
        ReportesPersona form = null;
        form = new ReportesPersona("AsigBienes");
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_rAsignBienesPersonaActionPerformed

    private void rSalConsumiblesPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSalConsumiblesPersonalActionPerformed
        ReportesPersona form = null;
        form = new ReportesPersona("SalConsumibles");
        Escritorio.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_rSalConsumiblesPersonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static javax.swing.JLabel lblAcceso;
    public static javax.swing.JLabel lblIdUsuario;
    public static javax.swing.JLabel lblNombre;
    public static javax.swing.JMenu mAreas;
    private javax.swing.JMenu mBienes;
    public static javax.swing.JMenuItem mConsultas;
    public static javax.swing.JMenuItem mConsumibles;
    public static javax.swing.JMenu mPersonal;
    public static javax.swing.JMenu mReportes;
    private javax.swing.JMenu mSalir;
    public static javax.swing.JMenu mUsuarios;
    private javax.swing.JMenu menuC;
    private javax.swing.JMenuItem rAltaBienesArea;
    private javax.swing.JMenuItem rAltaBienesFecha;
    private javax.swing.JMenuItem rAsignBienesArea;
    private javax.swing.JMenuItem rAsignBienesFecha;
    private javax.swing.JMenuItem rAsignBienesPersona;
    private javax.swing.JMenuItem rBajaBienesArea;
    private javax.swing.JMenuItem rBajaBienesFecha;
    private javax.swing.JMenuItem rConsumiblesCategoria;
    private javax.swing.JMenuItem rConsumiblesFecha;
    private javax.swing.JMenuItem rSalConsumiblesArea;
    private javax.swing.JMenuItem rSalConsumiblesFecha;
    private javax.swing.JMenuItem rSalConsumiblesPersonal;
    public static javax.swing.JMenuItem sAreas;
    private javax.swing.JMenuItem sBajasBienes;
    public static javax.swing.JMenuItem sBienes;
    private javax.swing.JMenuItem sCambioAsig;
    public static javax.swing.JMenuItem sConsultasBienes;
    public static javax.swing.JMenuItem sConsultasPersonal;
    private javax.swing.JMenuItem sEtiqueta;
    private javax.swing.JMenuItem sEtiquetaArea;
    private javax.swing.JMenuItem sEtiquetasAll;
    public static javax.swing.JMenuItem sPersonal;
    private javax.swing.JMenuItem sUsuarios;
    private javax.swing.JMenuItem sVale;
    private javax.swing.JMenuItem sValeRes;
    private javax.swing.JMenuItem wConsultaAsig;
    // End of variables declaration//GEN-END:variables
}
